In [2]:
import numpy as np


# Step 1: Create the dataset
X = np.array([
    [2, 5],
    [6, 4],
    [10, 11],
    [14, 14]
])

mean = np.mean(X, axis=0)
std_dev = np.std(X, axis=0)

# Standardize the dataset
X_standardized = (X - mean) / std_dev

print("Mean:\n", mean)
print("Standard Deviation:\n", std_dev)
print("Standardized Dataset:\n", X_standardized)
X = X_standardized

# Step 2: Calculate the covariance matrix
cov_matrix = np.cov(X.T)


# Step 3: Calculate the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

# Output the results
print("Covariance Matrix:\n", cov_matrix)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

#Step4 : Normalize the eigen vectors

norm_eigenvectors = eigenvectors / np.linalg.norm(eigenvectors, axis=0)

# Output the normalized eigenvectors
print("Normalized Eigenvectors:\n", norm_eigenvectors)

# Step 5: Project the original data onto the new basis (eigenvectors)


mean_X = np.mean(X, axis=0)
X_centered = X - mean_X
first_pc = norm_eigenvectors[:, 0]
second_pc = norm_eigenvectors[:, 1]
X_1D = np.dot(X_centered, first_pc)

# Output the new dataset
print("New Dataset after Projection:\n", X_1D)

X_1D2 = np.dot(X_centered,second_pc )

# Output the new dataset
print("New Dataset after Projection:\n", X_1D2)








Mean:
 [8.  8.5]
Standard Deviation:
 [4.47213595 4.15331193]
Standardized Dataset:
 [[-1.34164079 -0.84270097]
 [-0.4472136  -1.08347268]
 [ 0.4472136   0.60192927]
 [ 1.34164079  1.32424438]]
Covariance Matrix:
 [[1.33333333 1.22033231]
 [1.22033231 1.33333333]]
Eigenvalues:
 [2.55366564 0.11300102]
Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Normalized Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
New Dataset after Projection:
 [-1.54456287 -1.08235864  0.74185603  1.88506548]
New Dataset after Projection:
 [ 0.35280373 -0.44990311  0.1094005  -0.01230111]
